#!/usr/bin/python3
# Filename: rangeFind.py

# sample script to read range values from Maxbotix ultrasonic rangefinder

from time import sleep
import senor
import csv

serialPort = "/dev/serial0"
maxRange = 5000  # change for 5m vs 10m sensor
sleepTime = 2
minMM = 9999
maxMM = 0

while True:
    mm = senor.measure(serialPort)
    if mm >= maxRange:
        print("no target")
        sleep(sleepTime)
        continue
    if mm < minMM:
        minMM = mm
    if mm > maxMM:
        maxMM = mm
    

    print("distance:", mm, "  min:", minMM, "max:", maxMM)
    with open("SensorData.csv", "w", newline='') as f:
        writer = csv.writer(f)
        mm1 = str(mm)
        writer.writerow([mm1])
    sleep(sleepTime)
